"""PR3 — диалектный слой БД: qmark→$n, DDL для PG, portable upsert/_insert.

PG-интеграция помечена skipif и запускается только при ALBION_TEST_PG_DSN.
"""

import os

import pytest

from src.db.engine import ddl_pg, is_postgres, pg_dsn, translate_qmarks
from src.db.models import SCHEMA_SQL
from src.db.repository import (
    IdempotencyRepository,
    IncidentRepository,
    MeritHubEnrollmentRepository,
    ScheduledActionRepository,
    UserRepository,
    WorkflowRepository,
)

_PG_DSN = os.environ.get("ALBION_TEST_PG_DSN")
requires_pg = pytest.mark.skipif(not _PG_DSN, reason="ALBION_TEST_PG_DSN не задан")


# ── is_postgres / pg_dsn / translate_qmarks ──────────────────────────

def test_is_postgres():
    assert is_postgres("postgres://u:p@h/db")
    assert is_postgres("postgresql://u:p@h/db")
    assert is_postgres("postgresql+asyncpg://u:p@h/db")
    assert not is_postgres("albion.db")
    assert not is_postgres("sqlite+aiosqlite:///./albion.db")
    assert not is_postgres(None)


def test_pg_dsn_normalizes_scheme():
    assert pg_dsn("postgres://u:p@h/db") == "postgresql://u:p@h/db"
    assert pg_dsn("postgresql+asyncpg://u:p@h/db") == "postgresql://u:p@h/db"
    assert pg_dsn("postgresql://u:p@h/db") == "postgresql://u:p@h/db"


def test_translate_qmarks_basic():
    sql = "SELECT * FROM t WHERE a=? AND b IN (?,?) LIMIT ?"
    assert translate_qmarks(sql) == "SELECT * FROM t WHERE a=$1 AND b IN ($2,$3) LIMIT $4"


def test_translate_qmarks_skips_literals():
    sql = "SELECT 'что?' AS q, a FROM t WHERE a=? AND b='?'"
    out = translate_qmarks(sql)
    assert "'что?'" in out and "b='?'" in out
    assert "a=$1" in out
    # литерал с экранированной кавычкой
    assert translate_qmarks("SELECT 'It''s ?' , ? ") == "SELECT 'It''s ?' , $1 "


def test_ddl_pg_transforms():
    ddl = ddl_pg(SCHEMA_SQL)
    assert "PRAGMA" not in ddl
    assert "AUTOINCREMENT" not in ddl
    assert "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in ddl
    assert "CREATE TABLE IF NOT EXISTS users" in ddl
    assert "TIMESTAMP" not in ddl                          # → TEXT (ISO-строки)
    assert "TEXT DEFAULT (albion_now())" in ddl            # CURRENT_TIMESTAMP → f()


# ── sqlite-регрессия: portable-синтаксис работает как раньше ─────────

@pytest.mark.asyncio
async def test_insert_returns_id(db):
    uid = await UserRepository(db).create("9001", "parent", "Пользователь")
    assert uid == 1
    inc = await IncidentRepository(db).create(type="absence", status="pending")
    assert inc == 1
    wid = await WorkflowRepository(db).create("absence_notification", data={"x": 1})
    assert wid == 1


@pytest.mark.asyncio
async def test_find_by_json_text_compare(db):
    repo = WorkflowRepository(db)
    w1 = await repo.create("absence_notification", data={"incident_id": 5})
    await repo.create("absence_notification", data={"incident_id": 55})
    rows = await repo.find_by_json("incident_id", 5, limit=10)
    assert [r["id"] for r in rows] == [w1]          # 55 не матчится (R9-1)
    rows = await repo.find_by_json("incident_id", "5", limit=10)
    assert [r["id"] for r in rows] == [w1]          # '5' == 5 после CAST


@pytest.mark.asyncio
async def test_upsert_portable_syntax(db):
    repo = MeritHubEnrollmentRepository(db)
    await repo.add("C1", "mh1", student_name="Первый")
    await repo.add("C1", "mh1", student_name="Обновлённый")
    rows = await repo.list_by_class("C1")
    assert len(rows) == 1 and rows[0]["student_name"] == "Обновлённый"


@pytest.mark.asyncio
async def test_idempotency_on_conflict(db):
    repo = IdempotencyRepository(db)
    await repo.save("k1", "handler", response="r1")
    await repo.save("k1", "handler", response="r2")  # не падает, не дублирует
    assert await repo.exists("k1")


@pytest.mark.asyncio
async def test_claim_pending_atomic(db):
    repo = ScheduledActionRepository(db)
    from datetime import datetime, timezone
    aid = await repo.create(None, datetime.now(timezone.utc).isoformat(), "x", {})
    tasks = await repo.claim_pending()
    assert [t["id"] for t in tasks] == [aid]
    # второй claim не забирает running-задачу
    assert await repo.claim_pending() == []


# ── PG-интеграция (только с живым Postgres) ──────────────────────────

@requires_pg
@pytest.mark.asyncio
async def test_pg_smoke():
    """init_db на PG + roundtrip репозиториев на тех же запросах."""
    import uuid
    from src.db.migrations import init_db
    await init_db(_PG_DSN)
    uid = await UserRepository(_PG_DSN).create(f"pg_{uuid.uuid4().hex[:12]}", "parent", "Пользователь")
    assert uid
    inc = await IncidentRepository(_PG_DSN).create(type="absence", status="pending")
    wid = await WorkflowRepository(_PG_DSN).create("wf", data={"incident_id": inc})
    assert wid
    rows = await WorkflowRepository(_PG_DSN).find_by_json("incident_id", inc)
    assert rows and rows[0]["id"] == wid
    # scheduler: julianday/datetime compat-функции
    from datetime import datetime, timezone
    repo = ScheduledActionRepository(_PG_DSN)
    aid = await repo.create(None, datetime.now(timezone.utc).isoformat(), "a", {})
    tasks = await repo.claim_pending()
    assert any(t["id"] == aid for t in tasks)
