"""Диалектный слой БД: sqlite (aiosqlite, дефолт) | postgres (asyncpg).

PR3 плана этапа 1 (PHASE1_ARCHITECTURE.md §6). Репозитории пишут SQL в
SQLite-синтаксисе — здесь он исполняется на любом движке:

- '?' плейсхолдеры → $1,$2,… для PG (translate_qmarks, литералы не трогаем);
- специфичные sqlite-функции (julianday/datetime/json_extract)
  устанавливаются на стороне PG один раз в init_db (PG_COMPAT_SQL);
- DDL: PRAGMA выбрасываем, AUTOINCREMENT → IDENTITY (ddl_pg);
- .lastrowid → portable self._insert() (PG: RETURNING id).

DSN: postgres:// | postgresql:// | postgresql+asyncpg:// → asyncpg;
остальное — путь к sqlite-файлу. PG-соединения фиксируют TimeZone=UTC:
колонки времени хранят тот же ISO-текст UTC, что и sqlite.
"""

import logging
import re

import aiosqlite

logger = logging.getLogger(__name__)

try:
    import asyncpg  # опциональная зависимость: только для PG-деплоя
except ImportError:  # pragma: no cover - зависит от окружения
    asyncpg = None

_PG_SCHEMES = ("postgres://", "postgresql://", "postgresql+asyncpg://")


def is_postgres(dsn: str) -> bool:
    return str(dsn or "").startswith(_PG_SCHEMES)


def pg_dsn(dsn: str) -> str:
    """Нормализует URL к виду, который понимает asyncpg."""
    for scheme in ("postgresql+asyncpg://", "postgres://"):
        if dsn.startswith(scheme):
            return "postgresql://" + dsn.split("://", 1)[1]
    return dsn


def translate_qmarks(sql: str) -> str:
    """'?' → $1,$2,… — пропуская одинарные/двойные кавычки."""
    out: list[str] = []
    n = 0
    quote = None
    i = 0
    while i < len(sql):
        ch = sql[i]
        if quote:
            out.append(ch)
            if ch == quote:
                # 'It''s' — экранированная кавычка внутри литерала
                if i + 1 < len(sql) and sql[i + 1] == quote:
                    out.append(quote)
                    i += 1
                else:
                    quote = None
        elif ch in ("'", '"'):
            quote = ch
            out.append(ch)
        elif ch == "?":
            n += 1
            out.append(f"${n}")
        else:
            out.append(ch)
        i += 1
    return "".join(out)


def ddl_pg(script: str) -> str:
    """SCHEMA_SQL (sqlite-диалект) → DDL для Postgres.

    TIMESTAMP → TEXT: в sqlite эти колонки и так хранят ISO-строки
    (TIMESTAMP — лишь аффинность), а все параметры репозиториев — str.
    TEXT колонки сохраняют и формат, и лексикографические сравнения, и
    str-параметры asyncpg без правки вызывающего кода.
    """
    lines = [l for l in script.splitlines()
             if not l.strip().upper().startswith("PRAGMA")]
    sql = "\n".join(lines).replace(
        "INTEGER PRIMARY KEY AUTOINCREMENT",
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    sql = sql.replace("TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
                      "TEXT DEFAULT (albion_now())")
    return re.sub(r"\bTIMESTAMP\b", "TEXT", sql)


# Совместимость с sqlite-функциями в запросах репозиториев.
# Колонки времени — TEXT с ISO 'YYYY-MM-DDTHH:MM:SS.ffffff+00:00' (та же
# форма, что пишет Python .isoformat() — лексикографические сравнения
# валидны, т.к. оффсет всегда +00:00).
# julianday(text): epoch-секунды как у sqlite (ISO → timestamptz, naive =
# session-зона UTC — соединения фиксируют TimeZone=UTC).
# datetime('now'[, mod]) → тот же ISO-текст; albion_now() — DEFAULT для
# created_at/updated_at вместо CURRENT_TIMESTAMP (TEXT-колонка не
# принимает timestamptz-выражение без явного приведения).
# json_extract(data, '$.a.b') → text (аналог ->>/#>> в PG).
_NOW_FMT = "YYYY-MM-DD\"T\"HH24:MI:SS.US\"+00:00\""

# DROP: CREATE OR REPLACE не умеет менять return type существующей
# функции (миграция с ранних версий compat-слоя).
PG_COMPAT_SQL = f"""
DROP FUNCTION IF EXISTS julianday(timestamptz);
DROP FUNCTION IF EXISTS julianday(text);
DROP FUNCTION IF EXISTS datetime(text);
DROP FUNCTION IF EXISTS datetime(text, text);
DROP FUNCTION IF EXISTS json_extract(text, text);
DROP FUNCTION IF EXISTS albion_now();

CREATE OR REPLACE FUNCTION julianday(t text) RETURNS double precision
AS $$ SELECT extract(epoch from t::timestamptz) $$ LANGUAGE sql IMMUTABLE;

CREATE OR REPLACE FUNCTION albion_now() RETURNS text
AS $$ SELECT to_char(now() AT TIME ZONE 'UTC', '{_NOW_FMT}') $$ LANGUAGE sql STABLE;

CREATE OR REPLACE FUNCTION datetime(kind text) RETURNS text
AS $$ SELECT to_char(now() AT TIME ZONE 'UTC', '{_NOW_FMT}') $$ LANGUAGE sql STABLE;

CREATE OR REPLACE FUNCTION datetime(kind text, mod text) RETURNS text
AS $$
  SELECT to_char((now() + mod::interval) AT TIME ZONE 'UTC', '{_NOW_FMT}')
$$ LANGUAGE sql STABLE;

CREATE OR REPLACE FUNCTION json_extract(doc text, path text) RETURNS text
AS $$
  SELECT doc::jsonb #>> string_to_array(substring(path from 3), '.')
$$ LANGUAGE sql IMMUTABLE;
"""


class ExecResult:
    """Аналог aiosqlite.Cursor для вызывающих: .lastrowid и .rowcount."""

    def __init__(self, lastrowid=None, rowcount: int = 0):
        self.lastrowid = lastrowid
        self.rowcount = rowcount


class _SqliteConn:
    def __init__(self, conn: aiosqlite.Connection):
        self._c = conn

    async def execute(self, sql: str, params: tuple = ()) -> ExecResult:
        cur = await self._c.execute(sql, params)
        await self._c.commit()
        return ExecResult(lastrowid=cur.lastrowid, rowcount=cur.rowcount)

    async def insert(self, sql: str, params: tuple = (), id_col: str = "id"):
        res = await self.execute(sql, params)
        return res.lastrowid

    async def fetchone(self, sql: str, params: tuple = ()) -> dict | None:
        row = await (await self._c.execute(sql, params)).fetchone()
        return dict(row) if row else None

    async def fetchall(self, sql: str, params: tuple = ()) -> list[dict]:
        rows = await (await self._c.execute(sql, params)).fetchall()
        return [dict(r) for r in rows]

    async def executescript(self, script: str) -> None:
        await self._c.executescript(script)
        await self._c.commit()

    async def close(self) -> None:
        await self._c.close()


class _PgConn:
    def __init__(self, conn):
        self._c = conn

    async def execute(self, sql: str, params: tuple = ()) -> ExecResult:
        status = await self._c.execute(translate_qmarks(sql), *params)
        # asyncpg: 'INSERT 0 1' / 'UPDATE 3' / 'DELETE 2'
        parts = status.split()
        rc = int(parts[-1]) if parts and parts[-1].isdigit() else 0
        return ExecResult(rowcount=rc)

    async def insert(self, sql: str, params: tuple = (), id_col: str = "id"):
        row = await self._c.fetchrow(
            translate_qmarks(sql) + f" RETURNING {id_col}", *params)
        return row[id_col] if row else None

    async def fetchone(self, sql: str, params: tuple = ()) -> dict | None:
        row = await self._c.fetchrow(translate_qmarks(sql), *params)
        return dict(row) if row else None

    async def fetchall(self, sql: str, params: tuple = ()) -> list[dict]:
        rows = await self._c.fetch(translate_qmarks(sql), *params)
        return [dict(r) for r in rows]

    async def executescript(self, script: str) -> None:
        await self._c.execute(script)  # asyncpg принимает мультистейтменты

    async def close(self) -> None:
        await self._c.close()


class _ConnCtx:
    """async with connect(dsn) as db: унифицированное соединение."""

    def __init__(self, dsn: str):
        self.dsn = dsn
        self.conn = None

    async def __aenter__(self):
        if is_postgres(self.dsn):
            if asyncpg is None:
                raise RuntimeError(
                    "DATABASE_URL указывает на Postgres, но asyncpg не установлен "
                    "(requirements.txt)")
            self.conn = _PgConn(await asyncpg.connect(
                pg_dsn(self.dsn), server_settings={"TimeZone": "UTC"}))
        else:
            conn = await aiosqlite.connect(self.dsn)
            conn.row_factory = aiosqlite.Row
            self.conn = _SqliteConn(conn)
        return self.conn

    async def __aexit__(self, exc_type, exc, tb):
        if self.conn:
            await self.conn.close()
        return False


def connect(dsn: str) -> _ConnCtx:
    """Подключение по DSN: путь sqlite-файла или postgres:// URL."""
    return _ConnCtx(dsn)
